### ISSUE TITLE
Feature Request: No dependency on `echidna` in path

### ISSUE THREAD

**Issue by rappie** [crytic/diffusc#15]
### Describe the desired feature

I often use the latest `master` or specific branches. It would be nice to be able to run them simultaneously with `diffusc`

Suggestions

1. Add a `--echidna-binary` argument
2. Always use `./bin/echidna`

**Comment by webthethird** [comment]
This will be resolved soon :slightly_smiling_face:

**Comment by webthethird** [comment]
Resolved by #19

**Comment by rappie** [comment]
Would it be an idea to give the bundled Echidna a separate name, like `echidna-diffusc`? You can then install it to be in the system path like any other tool.

**Comment by webthethird** [comment]
That is certainly a solution I should have thought of earlier!
