### ISSUE TITLE
echidna: VM failed for unhandled reason, BadCheatCode 0xef9c9aac

### ISSUE THREAD

**Issue by rappie** [crytic/diffusc#6]
```echidna: VM failed for unhandled reason, BadCheatCode 0xef9c9aac. This shouldn't happen. Please file a ticket with this error message and steps to reproduce!```

How do I get the version of Echidna containing the new cheatcodes? I've installed the latest master using this command:

```
$ nix-env -i -f https://github.com/crytic/echidna/tarball/master
```

**Comment by webthethird** [comment]
The correct binary can be found in ./bin

**Comment by rappie** [comment]
If i'm not mistaken, `nix-env` downloads the latest source from master, builds it and copies the binary so that it's available in my path:

```
$ which echidna
/home/rappie/.nix-profile/bin/echidna
```

Could it be that I need to do something special to get echidna built with the latest HEVM?

**Comment by bohendo** [comment]
What does `echidna --version` (or `echidna-test --version`) return?

If the tarball installation didn't give you a functional version 2.2.0, you could also try:
```
git clone git@github.com:crytic/echidna.git
cd echidna
nix-build # or nix build .#echidna-bundle
nix-env -i ./result # or `nix profile install ./result`
```

**Comment by rappie** [comment]
```
❯ echidna --version
Echidna 2.2.0
❯ nix-env --uninstall echidna
uninstalling 'echidna-2.2.0'
❯ echidna --version
zsh: command not found: echidna
❯ nix-env -i -f https://github.com/crytic/echidna/tarball/master
warning: Nix search path entry '/nix/var/nix/profiles/per-user/rappie/channels' does not exist, ignoring
installing 'echidna-2.2.0'
❯ echidna --version
Echidna 2.2.0
```

Looks good, right? :slightly_smiling_face:

**Comment by webthethird** [comment]
I don't believe the latest Echidna source from master has the experimental forking cheat codes. Instead of building from source, try just doing `sudo cp ./bin/echidna /usr/local/bin`.

**Comment by rappie** [comment]
Ahh you ship your own special version of Echidna. I didn't realize you were talking about `./bin` in the diffusdc repo, sorry about that :sweat_smile: 

Will test this tomorrow, thanks!

**Comment by webthethird** [comment]
It's all good! Just goes to show that needing a special version of Echidna introduces a pain-point for users. Ideally the forking cheat codes will be integrated into HEVM/Echidna sooner rather than later, which should make installation more intuitive.

Closing this for now, but do let me know if you have any other issues. And thanks for your interest in the tool!
