### ISSUE TITLE
[Bug-Candidate]: ERROR:CryticCompile:Invalid solc compilation Error: Undeclared identifier

### ISSUE THREAD

**Issue by rappie** [crytic/diffusc#7]
### Describe the issue:

Compilation error when trying to run the tool

### Code example to reproduce the issue:

`diffusc 0x1091588cc431275f99dc5df311fd8e1ab81c89f3 0xea24e9bac006de9635ac7fa4d767ffb64fb5645c -v 0.8.7 -r -R https://eth.llamarpc.com`

### Version:

`diff-fuzz-upgrades: error: argument -v/--version: expected one argument` :smile: 

### Relevant log output:

```shell
* Calling echidna from ./ using echidna DiffFuzzUpgrades.sol --config CryticConfig.yaml --contract DiffFuzzUpgrades --format json --workers 1

echidna: Couldn't compile given file
stdout:
stderr:
INFO:CryticCompile:'solc --version' running
INFO:CryticCompile:'solc DiffFuzzUpgrades.sol --combined-json abi,ast,bin,bin-runtime,srcmap,srcmap-runtime,userdoc,devdoc,hashes,compact-format --allow-paths .,/home/rappie/Desktop/repos/diffusc' running
ERROR:CryticCompile:Invalid solc compilation Error: Undeclared identifier. Did you mean "oETHVaultCoreV1"?
--> DiffFuzzUpgrades.sol:166:59:
|
166 |         (bool successV1, bytes memory outputV1) = address(oETHVaultCore).call(
|                                                           ^^^^^^^^^^^^^

Error: Undeclared identifier. Did you mean "vaultCoreV2"?
--> DiffFuzzUpgrades.sol:174:59:
|
174 |         (bool successV2, bytes memory outputV2) = address(vaultCore).call(
|                                                           ^^^^^^^^^
```

**Comment by webthethird** [comment]
Looking into this now.

Also, I just created a PR which will change the solc version flags from `-v` and `--version` to `-V` and `--solc-version`, making `diffusc --version` behave as expected. Thanks for catching that!

**Comment by webthethird** [comment]
@rappie this issue should be resolved with the latest update to the main branch
